[package]
name = "endolphine"
authors = ["Tundra_Climate"]
description = "TUI file explorer made by Rust"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
dirs = "5.0.1"
ratatui = "0.26.3"
