[package]
name = "endolphine"
authors = ["Tundra_Climate"]
description = "TUI file explorer made by Rust"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
dirs = "5.0.1"
tokio = { version = "1.38.0", features = ["full"] }
tui-input = "*"
