[package]
name = "ep"
authors = ["Tundra_Climate"]
description = "TUI file explorer made by Rust"
version = "1.0.0"
edition = "2024"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "2.0.8"
once_cell = "1.20.2"
si-scale = "0.2.3"
walkdir = "2.5.0"
toml = "0.8.19"
serde = { version = "1.0.217", features = ["derive"] }
