use super::rgb;
use crate::scheme;

scheme!(
    fg: rgb("#FFFFFF"),
    fg_dark: rgb("#FFFFFF"),
    bg: crossterm::style::Color::Reset,
    bg_dark: crossterm::style::Color::Reset,
    label: rgb("#646464"),
    bar: rgb("#969696"),
    bar_dark: rgb("#787878"),
    path_picked: rgb("#969696"),
    bar_text: rgb("#282828"),
    bar_text_light: rgb("#646464"),
    perm_ty: rgb("#1EFAE6"),
    perm_r: rgb("#64DC96"),
    perm_w: rgb("#F0AA46"),
    perm_e: rgb("#FAFA3C"),
    row_file: rgb("#28DC28"),
    row_dir: rgb("#28C8C8"),
    row_symlink: rgb("#C828C8"),
    row_broken: rgb("#C80000"),
    bsize: rgb("#FAFA3C"),
    mod_time: rgb("#8246FF"),
    select: rgb("#EB8C00"),
    row_cursor: rgb("#555555"),
    input: crossterm::style::Color::Reset,
    widget_fg: rgb("#FFFFFF"),
    widget_fg_dark: rgb("#FFFFFF"),
    widget_bg: crossterm::style::Color::Reset,
    widget_bg_dark: crossterm::style::Color::Reset,
    widget_cursor: rgb("#464646"),
    menu_tag: rgb("#55F0B4"),
    search_sur: rgb("#55F0B4"),
);
