app_fg            = "#AFFFAF"
app_bg            = "#2D3B2D"
bar_fg            = "#C050A0"
bar_fg_light      = "#A46494"
bar_bg            = "#4D2C00"
item_bg_cursor    = "#80A080"
item_bg_select    = "#207090"
item_broken       = "#C80000"
item_dir          = "#A040D0"
item_file         = "#D040A0"
item_symlink      = "#8080FF"
item_sidemenu     = "#B29A20"
item_parts_bsize  = "#AAF0B0"
item_parts_lmd    = "#80AF80"
perm_ty           = "#909090"
perm_r            = "#90A040"
perm_w            = "#A0B050"
perm_x            = "#B0C060"
pwd_view          = "#AFFFAF"
pwd_pickouted     = "#96B696"
search_surround   = "#45FF94"
mode_normal       = "#686868"
mode_visual       = "#207090"
mode_input        = "#B0C060"
mode_search       = "#45FF94"
mode_menu         = "#C80000"
