app_fg            = "#FFFFFF"
app_bg            = "#1D1D1D"
bar_fg            = "#909090"
bar_fg_light      = "#A0A0A0"
bar_bg            = "#4F4F4F"
item_bg_cursor    = "#555555"
item_bg_select    = "#50FF50"
item_broken       = "#404040"
item_dir          = "#60AF60"
item_file         = "#00FF00"
item_symlink      = "#1F901F"
item_sidemenu     = "#1FFF1F"
item_parts_bsize  = "#1FFF1F"
item_parts_lmd    = "#1F9F1F"
perm_ty           = "#1FFF1F"
perm_r            = "#1FFF1F"
perm_w            = "#1FFF1F"
perm_x            = "#1FFF1F"
pwd_view          = "#FFFFFF"
pwd_pickouted     = "#969696"
search_surround   = "#1FFF1F"
mode_normal       = "#E0E0E0"
mode_visual       = "#50FF50"
mode_input        = "#1FFF1F"
mode_search       = "#1FFF1F"
mode_menu         = "#50FF50"
