app_fg = "#FFFFFF"
app_bg = "#3C3C3C"
bar_fg = "#282828"
bar_fg_light = "#646464"
bar_bg = "#969696"
item_bg_cursor = "#555555"
item_bg_select = "#EB8C00"
item_broken = "#C80000"
item_dir = "#28C8C8"
item_file = "#28DC28"
item_symlink = "#C828C8"
item_sidemenu = "#55F0B4"
item_parts_bsize = "#FAFA3C"
item_parts_lmd = "#8246FF"
perm_ty = "#1EFAE6"
perm_r = "#64DC96"
perm_w = "#F0AA46"
perm_x = "#FAFA3C"
pwd_view = "#FFFFFF"
pwd_pickouted = "#969696"
search_surround = "#55F084"
mode_normal = "#686868"
mode_visual = "#EB8C00"
mode_input = "#FAFA2C"
mode_search = "#55F084"
mode_menu = "#C000C0"
