app_fg            = "#FFFFFF"
app_bg            = "#505050"
bar_fg            = "#282828"
bar_fg_light      = "#3F3F3F"
bar_bg            = "#AF2020"
item_bg_cursor    = "#888888"
item_bg_select    = "#F2F2F2"
item_broken       = "#200000"
item_dir          = "#FFFFFF"
item_file         = "#FF2010"
item_symlink      = "#C828C8"
item_sidemenu     = "#60F050"
item_parts_bsize  = "#FFFFFF"
item_parts_lmd    = "#40FF60"
perm_ty           = "#FFFFFF"
perm_r            = "#60EF60"
perm_w            = "#EF4040"
perm_x            = "#FFFFFF"
pwd_view          = "#FFFFFF"
pwd_pickouted     = "#8F4040"
search_surround   = "#60F050"
mode_normal       = "#686868"
mode_visual       = "#F2F2F2"
mode_input        = "#FF2010"
mode_search       = "#60F050"
mode_menu         = "#FF2010"
