app_fg            = "#BEBEFF"
app_bg            = "#46465A"
bar_fg            = "#282828"
bar_fg_light      = "#646464"
bar_bg            = "#969696"
item_bg_cursor    = "#555555"
item_bg_select    = "#B4B4C8"
item_broken       = "#C80000"
item_dir          = "#28C8C8"
item_file         = "#3C3CFA"
item_symlink      = "#C828C8"
item_sidemenu     = "#55F0B4"
item_parts_bsize  = "#B4B4FF"
item_parts_lmd    = "#8282FF"
perm_ty           = "#1EFAE6"
perm_r            = "#6496DC"
perm_w            = "#46AAF0"
perm_x            = "#3CFAFA"
pwd_view          = "#BEBEFF"
pwd_pickouted     = "#6E6EB4"
search_surround   = "#55F0B4"
mode_normal       = "#686868"
mode_visual       = "#B4B4C8"
mode_input        = "#8282FF"
mode_search       = "#55F0B4"
mode_menu         = "#3C3CFA"
