app_fg            = "#000000"
app_bg            = "#C3C3C3"
bar_fg            = "#D7D7D7"
bar_fg_light      = "#9B9B9B"
bar_bg            = "#696969"
item_bg_cursor    = "#AAAAAA"
item_bg_select    = "#1473FF"
item_broken       = "#000000"
item_dir          = "#D73737"
item_file         = "#D723D7"
item_symlink      = "#37AF37"
item_sidemenu     = "#C80F4B"
item_parts_bsize  = "#0505C3"
item_parts_lmd    = "#7DB900"
perm_ty           = "#E10519"
perm_r            = "#9B2369"
perm_w            = "#0F55B9"
perm_x            = "#0505C3"
pwd_view          = "#000000"
pwd_pickouted     = "#696969"
search_surround   = "#AA0F4B"
mode_normal       = "#0A0A0A"
mode_visual       = "#1473FF"
mode_input        = "#707010"
mode_search       = "#35D064"
mode_menu         = "#C000C0"
