app_fg            = "#B4B4B4"
app_bg            = "#0F0F1E"
bar_fg            = "#0A0A0A"
bar_fg_light      = "#8C8C8C"
bar_bg            = "#555555"
item_bg_cursor    = "#373737"
item_bg_select    = "#EB8C00"
item_broken       = "#000000"
item_dir          = "#D2C864"
item_file         = "#A02828"
item_symlink      = "#32D22D"
item_sidemenu     = "#329632"
item_parts_bsize  = "#C8C800"
item_parts_lmd    = "#D25A00"
perm_ty           = "#DC0000"
perm_r            = "#A00000"
perm_w            = "#C86400"
perm_x            = "#C8C800"
pwd_view          = "#B4B4B4"
pwd_pickouted     = "#96B2B2"
search_surround   = "#55F0B4"
mode_normal       = "#686868"
mode_visual       = "#EB8C00"
mode_input        = "#FAFA2C"
mode_search       = "#32D22D"
mode_menu         = "#A00000"
