app_fg            = "#FFFFFF"
app_bg            = "#3C3C3C"
bar_fg            = "#282828"
bar_fg_light      = "#646464"
bar_bg            = "#969696"
item_bg_cursor    = "#555555"
item_bg_select    = "#BFBFBF"
item_broken       = "#2F2F2F"
item_dir          = "#AFAFAF"
item_file         = "#FFFFFF"
item_symlink      = "#6F6F6F"
item_sidemenu     = "#FFFFFF"
item_parts_bsize  = "#FFFFFF"
item_parts_lmd    = "#FFFFFF"
perm_ty           = "#FFFFFF"
perm_r            = "#FFFFFF"
perm_w            = "#FFFFFF"
perm_x            = "#FFFFFF"
pwd_view          = "#FFFFFF"
pwd_pickouted     = "#969696"
search_surround   = "#CFCFCF"
mode_normal       = "#686868"
mode_visual       = "#BFBFBF"
mode_input        = "#FFFFFF"
mode_search       = "#CFCFCF"
mode_menu         = "#FFFFFF"
