app_fg            = "#CFCFCF"
app_bg            = "#2B2B2B"
bar_fg            = "#282828"
bar_fg_light      = "#646464"
bar_bg            = "#96A696"
item_bg_cursor    = "#555555"
item_bg_select    = "#BFEECE"
item_broken       = "#AF8050"
item_dir          = "#80BFA0"
item_file         = "#BFFFBF"
item_symlink      = "#40A0FF"
item_sidemenu     = "#35E0A0"
item_parts_bsize  = "#00FFB0"
item_parts_lmd    = "#407060"
perm_ty           = "#60AF90"
perm_r            = "#90DFA0"
perm_w            = "#DFFFDF"
perm_x            = "#60AF70"
pwd_view          = "#CFCFCF"
pwd_pickouted     = "#969696"
search_surround   = "#55F0B4"
mode_normal       = "#686868"
mode_visual       = "#BFEECE"
mode_input        = "#80BFA0"
mode_search       = "#55F0B4"
mode_menu         = "#BFFFBF"
