app_fg            = "#FFFFFF"
app_bg            = "#141414"
bar_fg            = "#282828"
bar_fg_light      = "#646464"
bar_bg            = "#FFFFFF"
item_bg_cursor    = "#555555"
item_bg_select    = "#EB8C00"
item_broken       = "#000000"
item_dir          = "#00FF00"
item_file         = "#FF00FF"
item_symlink      = "#FFFF00"
item_sidemenu     = "#00FFFF"
item_parts_bsize  = "#FF0000"
item_parts_lmd    = "#00FFFF"
perm_ty           = "#FF00FF"
perm_r            = "#FF0000"
perm_w            = "#00FF00"
perm_x            = "#0000FF"
pwd_view          = "#FFFFFF"
pwd_pickouted     = "#969696"
search_surround   = "#55F0B4"
mode_normal       = "#686868"
mode_visual       = "#EB8C00"
mode_input        = "#FAFA2C"
mode_search       = "#55F084"
mode_menu         = "#C000C0"
