app_fg            = "#B4B4B4"
app_bg            = "#141414"
bar_fg            = "#DCDCDC"
bar_fg_light      = "#C8C8C8"
bar_bg            = "#3C3CB4"
item_bg_cursor    = "#3C3C55"
item_bg_select    = "#008CDB"
item_broken       = "#780000"
item_dir          = "#3232FF"
item_file         = "#9696FF"
item_symlink      = "#0000FF"
item_sidemenu     = "#55B4F0"
item_parts_bsize  = "#5A5AD8"
item_parts_lmd    = "#4646FF"
perm_ty           = "#6464A0"
perm_r            = "#6464BE"
perm_w            = "#6464DC"
perm_x            = "#6464FA"
pwd_view          = "#B4B4B4"
pwd_pickouted     = "#787878"
search_surround   = "#55B4F0"
mode_normal       = "#686868"
mode_visual       = "#008CDB"
mode_input        = "#4646FF"
mode_search       = "#55B4F0"
mode_menu         = "#9696FF"
