app_fg            = "#DCA0A0"
app_bg            = "#281414"
bar_fg            = "#282828"
bar_fg_light      = "#646464"
bar_bg            = "#DC1414"
item_bg_cursor    = "#555555"
item_bg_select    = "#EB8C00"
item_broken       = "#000000"
item_dir          = "#9B0000"
item_file         = "#FF9B00"
item_symlink      = "#C828C8"
item_sidemenu     = "#F05050"
item_parts_bsize  = "#B4B428"
item_parts_lmd    = "#B45000"
perm_ty           = "#C81414"
perm_r            = "#C83C14"
perm_w            = "#C87814"
perm_x            = "#C8B414"
pwd_view          = "#DCA0A0"
pwd_pickouted     = "#96A0A0"
search_surround   = "#EB8C00"
mode_normal       = "#686868"
mode_visual       = "#EB8C00"
mode_input        = "#FAFA2C"
mode_search       = "#EB8C00"
mode_menu         = "#FF9B00"
