mod bloom;
mod collapse;
mod dark;
mod dark_no_bg;
mod holiday;
mod ice;
mod light;
mod light_no_bg;
mod mars;
mod monochrome;
mod mossy;
mod neon;
mod nept;
mod volcano;

pub use bloom::SCHEME as Bloom;
pub use collapse::SCHEME as Collapse;
pub use dark::SCHEME as Dark;
pub use dark_no_bg::SCHEME as DarkNoBg;
pub use holiday::SCHEME as Holiday;
pub use ice::SCHEME as Ice;
pub use light::SCHEME as Light;
pub use light_no_bg::SCHEME as LightNoBg;
pub use mars::SCHEME as Mars;
pub use monochrome::SCHEME as Monochrome;
pub use mossy::SCHEME as Mossy;
pub use neon::SCHEME as Neon;
pub use nept::SCHEME as Nept;
pub use volcano::SCHEME as Volcano;
